# Build stage
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
COPY pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build

# Production stage
FROM node:22-alpine

WORKDIR /app
RUN npm install -g pnpm
COPY --from=build /app ./
EXPOSE 3000

CMD ["pnpm", "start"]